version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/"
    labels:
      - "dependency"
      - "docker"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
