version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/"
    assignees:
      - "dependabot"
    reviewers:
      - "bybatkhuu"
      - "Copilot"
    labels:
      - "dependency"
      - "docker"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
