changelog:
  categories:
    - title: 💥 Breaking Changes
      labels:
        - breaking
        - breaking-change
        - breaking-changes
        - major
        - semver-major
    - title: ✨ Features
      labels:
        - feature
        - features
        - enhancement
        - minor
        - semver-minor
    - title: 🐛 Fixes
      labels:
        - fix
        - bug
        - bugs
        - bugfix
        - patch
        - semver-patch
    - title: 📝 Documentation
      labels:
        - docs
        - documentation
        - readme
        - changelog
        - markdown
    - title: 🧪 Tests
      labels:
        - test
        - tests
        - testing
        - unit-test
        - integration-test
        - e2e-test
        - stress-test
    - title: ⚡️ Performance
      labels:
        - perf
        - performance
        - speed
        - fast
    - title: 👷 CI/CD
      labels:
        - ci
        - cicd
        - ci/cd
        - build
        - deploy
        - deployment
        - pipeline
        - github-actions
        - automation
    - title: 🎨 Styles
      labels:
        - style
        - styles
        - format
        - formatting
        - lint
        - linting
    - title: 🚑️ Critical Hotfix
      labels:
        - hotfix
        - critical
        - urgent
        - emergency
    - title: 🔒️ Security
      labels:
        - secure
        - security
        - vulnerability
        - exploit
        - hacker
        - cve
    - title: 📌 Dependencies
      labels:
        - dependencies
        - dependency
        - dependabot
    - title: 🐳 Docker
      labels:
        - docker
        - dockerfile
        - docker-compose
        - compose
        - container
    - title: 🔨 Scripts
      labels:
        - script
        - scripts
        - tool
        - tools
    - title: 🗑️ Deprecation
      labels:
        - deprecate
        - deprecated
        - deprecation
    - title: 🧹 Chores
      labels:
        - chore
        - maintenance
    - title: 💬 Other
      labels:
        - "*"
