services:
  certbot:
    image: ${IMG_REGISTRY:-bybatkhuu}/certbot:2.1.0-240222
    restart: unless-stopped
    environment:
      - TERM=${TERM:-xterm}
      - TZ=${TZ:-Asia/Seoul}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - CERTBOT_DOMAINS=${CERTBOT_DOMAINS}
      - CERTBOT_DNS_TIMEOUT=${CERTBOT_DNS_TIMEOUT:-30}
    volumes:
      - "./volumes/storage/nginx/www/.well-known/acme-challenge:/var/www/.well-known/acme-challenge"
      - "./volumes/storage/nginx/ssl:/etc/letsencrypt"
    network_mode: host
    tty: true

  nginx:
    image: ${IMG_REGISTRY:-bybatkhuu}/nginx:2.2.1-240319
    depends_on:
      - certbot
    restart: unless-stopped
    environment:
      - TERM=${TERM:-xterm}
      - TZ=${TZ:-Asia/Seoul}
    volumes:
      - "./volumes/storage/nginx/logs:/var/log/nginx"
      - "./volumes/storage/nginx/www:/var/www"
      - "./volumes/storage/nginx/ssl:/etc/nginx/ssl"
      - "./volumes/storage/nginx/configs/sites-enabled:/etc/nginx/sites-enabled"
      - "./volumes/storage/nginx/configs/templates:/etc/nginx/templates"
    network_mode: host
    tty: true
    command: ["--https=lets"]
