services:
  certbot:
    image: bybatkhuu/certbot:3.1.5-260829
    restart: always
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-UTC}
      CERTBOT_EMAIL: ${CERTBOT_EMAIL:?}
      CERTBOT_DOMAINS: "${CERTBOT_DOMAINS:?}"
      CERTBOT_DNS_TIMEOUT: ${CERTBOT_DNS_TIMEOUT:-30}
    volumes:
      - "./volumes/secrets/certbot/credentials:/root/.secrets/certbot"
      - "./volumes/secrets/certbot/ssl:/etc/letsencrypt"
      - "./volumes/storage/nginx/www/.well-known/acme-challenge:/var/www/.well-known/acme-challenge"
    network_mode: host
    tty: true

  nginx:
    image: bybatkhuu/nginx:3.3.3-260829
    depends_on:
      - certbot
    restart: always
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-UTC}
      NGINX_BASIC_AUTH_USER: ${NGINX_BASIC_AUTH_USER:?}
      NGINX_BASIC_AUTH_PASS: "${NGINX_BASIC_AUTH_PASS:?}"
    volumes:
      - "./volumes/secrets/certbot/ssl:/etc/nginx/ssl"
      - "./volumes/configs/nginx/templates:/etc/nginx/templates"
      - "./volumes/configs/nginx/sites-enabled:/etc/nginx/sites-enabled"
      - "./volumes/storage/nginx/logs:/var/log/nginx"
      - "./volumes/storage/nginx/www:/var/www"
    network_mode: host
    command: ["--https=lets"]
    tty: true
