version: "3.8"

services:
  certbot:
    image: ${IMG_NAMESCAPE}/certbot:1.2.0-230406
    restart: unless-stopped
    environment:
      - TERM=${TERM:-xterm}
      - TZ=${TZ:-Asia/Seoul}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - CERTBOT_DOMAINS=${CERTBOT_DOMAINS}
      - CERTBOT_DNS_TIMEOUT=${CERTBOT_DNS_TIMEOUT:-30}
    volumes:
      - "./volumes/storage/nginx/ssl:/etc/letsencrypt"
      - "./volumes/storage/nginx/www/.well-known/acme-challenge:/var/www/.well-known/acme-challenge"
      - "./volumes/storage/certbot/logs:/var/log/letsencrypt"
    network_mode: host
    tty: true

  nginx:
    image: ${IMG_NAMESCAPE}/nginx:1.1.0-230406
    depends_on:
      - certbot
    restart: unless-stopped
    environment:
      - TERM=${TERM:-xterm}
      - TZ=${TZ:-Asia/Seoul}
    volumes:
      - "./volumes/storage/nginx/configs/templates:/etc/nginx/templates"
      - "./volumes/storage/nginx/www:/var/www"
      - "./volumes/storage/nginx/ssl:/etc/nginx/ssl"
      - "./volumes/storage/nginx/logs:/var/log/nginx"
    network_mode: host
    tty: true
    command: ["--https=lets"]
