services:
  certbot:
    image: ${IMG_REGISTRY:-bybatkhuu}/certbot:latest
    # env_file:
    #   - .env
    volumes:
      # - "./volumes/storage/certbot/secrets:/root/.secrets/certbot"
      # - "./volumes/storage/certbot/secrets:/root/.aws"
      - "./volumes/src/sidecar.certbot/scripts/docker/certbot-permissions.sh:/usr/local/bin/certbot-permissions.sh"
      - "./volumes/src/sidecar.certbot/scripts/docker/certbot-deploy-hook.sh:/usr/local/bin/certbot-deploy-hook.sh"
      - "./volumes/src/sidecar.certbot/scripts/docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./volumes/.vscode-server:/root/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: 256M
    # network_mode: bridge
    # ports:
    #   - "${CERTBOT_PORT:-80}:80"
    # command: ["--new=webroot"]
    # command: ["--renew=standalone"]
    # command: ["--disable-renew"]
    # command: ["--dns=cloudflare"]
    # command: ["--dns=digitalocean"]
    # command: ["--dns=route53"]
    # command: ["--dns=google"]
    # command: ["--dns=godaddy"]
    # command: ["/bin/bash"]

  nginx:
    image: ${IMG_REGISTRY:-bybatkhuu}/nginx:latest
    # env_file:
    #   - .env
    # environment:
    #   - NGINX_BASIC_AUTH_USER=${NGINX_BASIC_AUTH_USER}
    #   - NGINX_BASIC_AUTH_PASS=${NGINX_BASIC_AUTH_PASS}
    volumes:
      - "./volumes/src/server.nginx-template/src/configs/nginx.conf:/etc/nginx/nginx.conf"
      - "./volumes/src/server.nginx-template/scripts/docker/nginx-reload.sh:/usr/local/bin/nginx-reload.sh"
      - "./volumes/src/server.nginx-template/scripts/docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./volumes/.vscode-server:/root/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "1.0"
    #       memory: 1G
    # network_mode: bridge
    # ports:
    #   - "${NGINX_HTTPS_PORT:-443}:443"
    #   - "${NGINX_HTTP_PORT:-80}:80"
    # command: ["--https=self"]
    # command: ["--https=valid"]
    # command: ["--https=lets"]
    # command: ["/bin/bash"]
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:${NGINX_HTTP_PORT:-80}"]
    #   start_period: 15s
    #   start_interval: 1s
    #   interval: 5m
    #   timeout: 5s
    #   retries: 3
