name: Update Dependencies

on:
  workflow_dispatch:

jobs:
  update_deps:
    name: Update Dependencies
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      actions: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          ./scripts/depends.sh -b -c -p -r
